variables:
  - name: _BuildConfig
    value: Release
  - name: _TeamName
    value: AspNetCore
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: true
  - name: _PublishUsingPipelines
    value: true
  - name: _DotNetArtifactsCategory
    value: ENTITYFRAMEWORKCORE
  - name: _CosmosConnectionUrl
    value: https://localhost:8081
  - name: _CosmosToken
    value: C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==
  - ${{ if ne(variables['System.TeamProject'], 'public') }}:
    - group: DotNet-MSRC-Storage
    - name: _InternalRuntimeDownloadArgs
      value: /p:DotNetRuntimeSourceFeed=https://dotnetclimsrc.blob.core.windows.net/dotnet
             /p:DotNetRuntimeSourceFeedKey=$(dotnetclimsrc-read-sas-token-base64)
  - ${{ if eq(variables['System.TeamProject'], 'public') }}:
    - name: _InternalRuntimeDownloadArgs
      value: ''
    
  # used for post-build phases, internal builds only
  - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
    - group: DotNet-EFCore-SDLValidation-Params
- name: _HelixType
    value: build/product
  - name: _HelixSource
    value: pr/dotnet/efcore/$(Build.SourceBranch)
  - name: _HelixTestType
    value: test/product/
  - name: _XUnitProject
    value: $(Build.SourcesDirectory)/test/EFCore.Tests/EFCore.Tests.csproj
  - name: _XUnitPublishTargetFramework
    value: netcoreapp3.1
  - name: _XUnitRuntimeTargetFramework
    value: netcoreapp2.0
  - name: _XUnitRunnerVersion
    value: 2.4.1
  - name: _DotNetCliPackageType
    value: sdk
  - name: _DotNetCliVersion
    value: 3.1.100
  - name: _HelixAccessToken
    value: ''

trigger:
  - master
  - release/*
  - feature/*
  - internal/release/3.*

pr: ['*']

stages:
 - stage: build
   displayName: Build
   jobs:
    - template: /eng/common/templates/job/job.yml
      parameters:
        name: Windows_NT
        enableTelemetry: true
        enablePublishBuildArtifacts: true
        helixRepo: dotnet/efcore
        agentOs: Windows
        steps:
        - template: /eng/common/templates/steps/send-to-helix.yml
          parameters:
            HelixSource: $(_HelixSource)
            HelixType: $(_HelixTestType)
            HelixTargetQueues: Windows.10.Amd64.Open
            XUnitProjects: $(_XUnitProject)
            XUnitPublishTargetFramework: $(_XUnitPublishTargetFramework)
            XUnitRuntimeTargetFramework: $(_XUnitRuntimeTargetFramework)
            XUnitRunnerVersion: $(_XUnitRunnerVersion)
            IncludeDotNetCli: true
            DotNetCliPackageType: $(_DotNetCliPackageType)
            DotNetCliVersion: $(_DotNetCliVersion)
            EnableXUnitReporter: true
            WaitForWorkItemCompletion: true
            Creator: efcore
            condition: succeeded()
        